# Generated by Django 5.0.6 on 2024-06-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='adress',
            new_name='Adresse',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='num_bathrooms',
            new_name='Nombre_chambre',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='num_bedrooms',
            new_name='Nombre_salle_bain',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='price',
            new_name='Prix',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='square',
            new_name='Surface',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='title',
        ),
        migrations.AddField(
            model_name='listings',
            name='Action_commerciale',
            field=models.CharField(default='vendre', max_length=150),
        ),
        migrations.AddField(
            model_name='listings',
            name='Titre',
            field=models.CharField(default='title', max_length=150),
        ),
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='listings',
            name='type_bien',
            field=models.CharField(default='app/villa...', max_length=150),
        ),
    ]
