# Generated by Django 5.0.6 on 2024-06-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='username',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='email',
            field=models.CharField(default='email', max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message',
            field=models.CharField(default='message', max_length=500),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='subject', max_length=150),
        ),
    ]
